export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";

export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY";
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";

export const GET_ALL_SUBCATEGORIES_ON_CTEGORY = "GET_ALL_SUBCATEGORIES_ON_CTEGORY"
export const CREATE_SUBCATEGORIES_ON_CTEGORY = "CREATE_SUBCATEGORIES_ON_CTEGORY"

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const CREATE_PRODUCT = "CREATE_PRODUCT"

export const GET_ERROR = "GET_ERROR";

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT"
export const PRODUCT_LIKE = "PRODUCT_LIKE"


export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PEODUCT = "UPDATE_PEODUCT"

export const SIGNUP = "SIGNUP"
export const LOGIN = "LOGIN"
export const GET_LOGGED_USER = "GET_LOGGED_USER"

export const FORGOT_PASSWORD = "FORGOT_PASSWORD"

export const VERIFY_RESET_CODE = "VERIFY_RESET_CODE"
export const RESET_PASSWORD = "RESET_PASSWORD"

export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS"
export const CREATE_REVIEW = "CREATE_REVIEW"
export const DELETE_REVIEW = "DELETE_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const GET_ALL_WishList = "GET_ALL_WishList"
export const DELETE_PROD_FROM_WISHLIST = "DELETE_PROD_FROM_WISHLIST"


export const GET_ALL_COUPONS = "GET_ALL_COUPONS"
export const CREATE_COUPONS = "CREATE_COUPONS"
export const UPDATE_COUPONS = "UPDATE_COUPONS"
export const DELETE_COUPON = "DELETE_COUPON"
export const GET_COUPON = "GET_COUPON"



export const GET_ADDRESSES = "GET_ADDRESSES"