export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";

export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY";
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";

export const GET_ALL_SUBCATEGORIES_ON_CTEGORY="GET_ALL_SUBCATEGORIES_ON_CTEGORY"
export const CREATE_SUBCATEGORIES_ON_CTEGORY="CREATE_SUBCATEGORIES_ON_CTEGORY"

export const GET_ALL_PRODUCT="GET_ALL_PRODUCT"
export const CREATE_PRODUCT="CREATE_PRODUCT"

export const GET_ERROR = "GET_ERROR";


